server:
  port: 3000
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wsyu9a?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: wsyu9a
    password: 123456
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 连接超时时间
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭二级缓存
    cache-enabled: false
    # 关闭延迟加载
    lazy-loading-enabled: false
  type-aliases-package: com.wsyu9a.entity

logging:
  level:
    com.wsyu9a: debug
    org.springframework.web: DEBUG 

jwt:
  secret: wsyu9a_jwt_secret_key_must_be_at_least_64_bytes_long_for_hs512_algorithm_security
  expiration: 86400000  # 24小时，单位：毫秒 

problem:
  docker-compose:
    upload-path: ${user.dir}/upload/docker  # 使用项目根目录下的 upload/docker 目录 
  upload:
    readme-path: ${user.dir}/upload/readme  # 使用项目根目录下的 upload/readme 目录 

# Docker配置
docker:
  config:
    enabled: true
    default-timeout: 300
    max-containers: 50
    auto-clean: true 